name: Setup SDKs
description: Setup SDKs using SDKMAN!

runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: ~/.sdkman/tmp
        key: '${{ runner.os }}-sdkman'
        restore-keys: '${{ runner.os }}-sdkman'

    - uses: sdkman/sdkman-action@main
