name: 'Gradle Validation'
on:
  push:
    paths:
      - 'gradle/wrapper/**'

jobs:
  validate-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1