name: 'Gradle Wrapper Validation'
on:
  - push
  - pull_request

jobs:
  validate-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1